# Generated by Django 3.2.6 on 2021-09-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='person',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
