# Generated by Django 3.2.9 on 2021-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210903_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(default='default title', max_length=40),
            preserve_default=False,
        ),
    ]
